<?php

use Illuminate\Database\Seeder;

class CpHazardActionRecommendationTableSeedMasterSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cp_hazard_action_recommendation')->delete();
        
        \DB::table('cp_hazard_action_recommendation')->insert(array (
            0 => 
            array (
                'id' => 411,
            'description' => 'No previous recommendation(s)',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 412,
                'description' => 'Air Test',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 413,
                'description' => 'Undertake 4-stage Air Monitoring under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 412,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 414,
                'description' => 'Undertake 4-stage Air Monitoring under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 412,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 415,
                'description' => 'Undertake Background Air Test under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 412,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 416,
                'description' => 'Undertake Background Air test under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 412,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 417,
                'description' => 'Undertake Immediate Air Monitoring under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 412,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 418,
                'description' => 'Undertake Immediate Air Monitoring under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 412,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 419,
                'description' => 'Undertake Reassurance Air Test under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 412,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 420,
                'description' => 'Undertake Reassurance Air Test under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 412,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 421,
                'description' => 'Apply Caution',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 422,
                'description' => 'Apply Caution',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 421,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 423,
                'description' => 'Apply Caution due to Limited Inspection',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 421,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 424,
                'description' => 'Apply Caution due to Possible ACM Presence',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 421,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 425,
                'description' => 'Apply Caution due to Possible ACMs Within',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 421,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 426,
                'description' => 'Clean',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 427,
            'description' => 'Class H Shadow Vacuum (Where Wetting Incomplete/unsafe)',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 426,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 428,
                'description' => 'Undertake Environmental Clean under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 426,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 429,
                'description' => 'Undertake Environmental Clean under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 426,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 430,
                'description' => 'Encapsulate',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 431,
                'description' => 'Encapsulate & Label',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 430,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 432,
                'description' => 'Encapsulate under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 430,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 433,
                'description' => 'Encapsulate under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 430,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 434,
                'description' => 'Encapsulate using Board & Seal under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 430,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 435,
                'description' => 'Encapsulate using Board & Seal under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 430,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 436,
                'description' => 'Encapsulate using Barrier/sealer Coating under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 430,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 437,
                'description' => 'Encapsulate using Barrier/sealer Coating under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 430,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 438,
                'description' => 'Encapsulate using Polythene & Tape under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 430,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 439,
                'description' => 'Encapsulate using Polythene &Tape under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 430,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 440,
                'description' => 'Enclose',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 441,
                'description' => 'Further Investigation
Required prior to Remedial Works',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 442,
                'description' => 'Label',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 443,
                'description' => 'Manage',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 444,
                'description' => 'Annually Re-inspect',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 443,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 445,
                'description' => 'Frequently Re-inspect due to Activity within Area',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 443,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 446,
                'description' => 'Manage',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 443,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 447,
                'description' => 'Manage & Annually Re-inspect',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 443,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 448,
                'description' => 'Manage & Label',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 443,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 449,
                'description' => 'Manage, Encapsulate, Label & Annually Re-inspect',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 443,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 450,
                'description' => 'Manage, Label & Annually Re-inspect',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 443,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 451,
                'description' => 'Monitor',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 452,
                'description' => 'Miscellaneous',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 453,
                'description' => 'Immediate Action Required',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 452,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 454,
                'description' => 'No Action Required',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 452,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 455,
                'description' => 'Control Airborne Emissions by Pre-wetting Sampled Material',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 452,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 456,
                'description' => 'Repair',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 457,
                'description' => 'Repair Damaged Area',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 456,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 458,
                'description' => 'Repair Damaged Area & Update Register upon Completion',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 456,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 459,
                'description' => 'Remove',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 461,
            'description' => 'Remove ACM (Bonded) under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 462,
            'description' => 'Remove ACM (Bonded) under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 463,
            'description' => 'Remove ACM (Fibrous) under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 464,
            'description' => 'Remove ACM (Fibrous) under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 465,
                'description' => 'Remove ACM before Refurb. Work under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 466,
                'description' => 'Remove ACM before Refurb. Work under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 467,
                'description' => 'Remove Debris & Encapsulate under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 468,
                'description' => 'Remove Debris & Encapsulate under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 469,
            'description' => 'Remove Item(s) within Vicinity of ACM',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 470,
                'description' => 'Remove under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 471,
                'description' => 'Remove under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 472,
                'description' => 'Remove/replace using Non-ACM ',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 473,
                'description' => 'Remove/replace using Non-ACM under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 474,
                'description' => 'Remove/replace using Non-ACM under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 475,
                'description' => 'Restrict Access',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 476,
                'description' => 'Restrict Access and Suitably Warn ',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 475,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 477,
                'description' => 'Restrict Access into Room/location',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 475,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 478,
                'description' => 'Restrict Access until Debris Cleared under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 475,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 479,
                'description' => 'Restrict Access until Debris Cleared under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 475,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 480,
                'description' => 'Restrict Access until Enviro. Clean under FCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 475,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 481,
                'description' => 'Restrict Access until Enviro. Clean under PCC by FLC',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 475,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 482,
                'description' => 'Restrict Access until Item Confirmed',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 475,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 483,
                'description' => 'Restrict Access until Remedial Work Undertaken',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 475,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 484,
                'description' => 'Restrict Access until Removal Work Undertaken',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 475,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 485,
                'description' => 'Sample',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 486,
            'description' => 'Take Additional Sample(s) to Confirm Same ACM Throughout',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 485,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 487,
            'description' => 'Take Additional Sample(s) to Confirm Material Composition',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 485,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 488,
            'description' => 'Take Sample(s) to Confirm Material Composition',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 485,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 489,
                'description' => 'Treat',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 490,
                'description' => 'Treat All Waste as ACM',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 489,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 491,
                'description' => 'Treat as Uniform Material Composition',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 489,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 492,
                'description' => 'Treat as Uniform Throughout',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 489,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 493,
                'description' => 'Other',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => -1,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 2162,
                'description' => 'Encapsulate',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 430,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 2163,
                'description' => 'Remove',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 459,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 2190,
                'description' => 'Further Investigation Required',
                'dropdown_item_id' => 7,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}