<?php

use Illuminate\Database\Seeder;

class CpHazardMeasurementTableSeedMasterSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cp_hazard_measurement')->delete();
        
        \DB::table('cp_hazard_measurement')->insert(array (
            0 => 
            array (
                'id' => 367,
                'description' => 'Measurements',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 0,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 368,
                'description' => 'ft',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 369,
                'description' => 'ft²',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 370,
                'description' => 'ft³',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 371,
                'description' => 'm',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 372,
                'description' => 'm²',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 373,
                'description' => 'm³',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 374,
            'description' => 'Box(es)',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 375,
                'description' => 'Number',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 376,
            'description' => 'Item(s)',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 377,
            'description' => 'Unit(s)',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 378,
                'description' => 'Unknown',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 379,
                'description' => 'Other',
                'dropdown_item_id' => 4,
                'order' => 127,
                'score' => 0,
                'other' => -1,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 697,
                'description' => 'Small Amounts',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 777,
                'description' => 'Trace Amounts',
                'dropdown_item_id' => 4,
                'order' => 0,
                'score' => 0,
                'other' => 0,
                'decommissioned' => 0,
                'parent_id' => 367,
                'removal_cost' => NULL,
                'deleted_by' => NULL,
                'created_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}