<?php

use Illuminate\Database\Seeder;

class CpTempValidationTableSeedMasterSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cp_temp_validation')->delete();
        
        \DB::table('cp_temp_validation')->insert(array (
            0 => 
            array (
                'id' => 1,
                'type_id' => 12,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => '60',
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => '50',
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '60',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => '50',
                'return_temp_max' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'type_id' => 8,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => '60',
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => '50',
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '60',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => '50',
                'return_temp_max' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'type_id' => 9,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => '60',
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => '50',
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '60',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => '50',
                'return_temp_max' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'type_id' => 104,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '50',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'type_id' => 80,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '50',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'type_id' => 73,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '50',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'type_id' => 74,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '50',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'type_id' => 75,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '50',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'type_id' => 76,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '50',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'type_id' => 77,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '50',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'type_id' => 67,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '50',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'type_id' => 68,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '50',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'type_id' => 69,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '50',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'type_id' => 70,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '50',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'type_id' => 71,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '50',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'type_id' => 25,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => '20',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'type_id' => 26,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => '20',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'type_id' => 27,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => '20',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'type_id' => 28,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => '20',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'type_id' => 29,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => '20',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'type_id' => 30,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => '20',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'type_id' => 44,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '50',
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'type_id' => 86,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '50',
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'type_id' => 93,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '50',
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'type_id' => 94,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '50',
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'type_id' => 95,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '50',
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'type_id' => 96,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '50',
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'type_id' => 97,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '50',
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'type_id' => 98,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '50',
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            29 => 
            array (
                'id' => 36,
                'type_id' => 18,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => '20',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            30 => 
            array (
                'id' => 37,
                'type_id' => 19,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => '20',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            31 => 
            array (
                'id' => 38,
                'type_id' => 20,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => '20',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            32 => 
            array (
                'id' => 39,
                'type_id' => 21,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => '20',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            33 => 
            array (
                'id' => 40,
                'type_id' => 22,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => '20',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            34 => 
            array (
                'id' => 41,
                'type_id' => 23,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => '20',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            35 => 
            array (
                'id' => 43,
                'type_id' => 73,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '39',
                'flow_temp_max' => '43',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            36 => 
            array (
                'id' => 44,
                'type_id' => 74,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '39',
                'flow_temp_max' => '43',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            37 => 
            array (
                'id' => 45,
                'type_id' => 75,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '39',
                'flow_temp_max' => '43',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            38 => 
            array (
                'id' => 46,
                'type_id' => 76,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '39',
                'flow_temp_max' => '43',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            39 => 
            array (
                'id' => 47,
                'type_id' => 77,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '39',
                'flow_temp_max' => '43',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            40 => 
            array (
                'id' => 48,
                'type_id' => 67,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '39',
                'flow_temp_max' => '43',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            41 => 
            array (
                'id' => 49,
                'type_id' => 68,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '39',
                'flow_temp_max' => '43',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            42 => 
            array (
                'id' => 50,
                'type_id' => 69,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '39',
                'flow_temp_max' => '43',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            43 => 
            array (
                'id' => 51,
                'type_id' => 70,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '39',
                'flow_temp_max' => '43',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            44 => 
            array (
                'id' => 52,
                'type_id' => 71,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '39',
                'flow_temp_max' => '43',
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            45 => 
            array (
                'id' => 53,
                'type_id' => 44,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '39',
                'top_temp_max' => '43',
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            46 => 
            array (
                'id' => 54,
                'type_id' => 86,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '39',
                'top_temp_max' => '43',
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            47 => 
            array (
                'id' => 55,
                'type_id' => 93,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '39',
                'top_temp_max' => '43',
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            48 => 
            array (
                'id' => 56,
                'type_id' => 94,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '39',
                'top_temp_max' => '43',
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            49 => 
            array (
                'id' => 57,
                'type_id' => 95,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '39',
                'top_temp_max' => '43',
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            50 => 
            array (
                'id' => 58,
                'type_id' => 96,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '39',
                'top_temp_max' => '43',
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            51 => 
            array (
                'id' => 59,
                'type_id' => 97,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '39',
                'top_temp_max' => '43',
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            52 => 
            array (
                'id' => 60,
                'type_id' => 98,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '39',
                'top_temp_max' => '43',
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            53 => 
            array (
                'id' => 61,
                'type_id' => 113,
                'tmv' => 1,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => '39',
                'top_temp_max' => '43',
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => '20',
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            54 => 
            array (
                'id' => 62,
                'type_id' => 113,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => '50',
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => NULL,
                'stored_temp_min' => NULL,
                'stored_temp_max' => NULL,
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            55 => 
            array (
                'id' => 63,
                'type_id' => 24,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => '20',
                'stored_temp_min' => NULL,
                'stored_temp_max' => '20',
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
            56 => 
            array (
                'id' => 64,
                'type_id' => 17,
                'tmv' => 0,
                'flow_temp_gauge_value_min' => NULL,
                'flow_temp_gauge_value_max' => NULL,
                'return_temp_gauge_value_min' => NULL,
                'return_temp_gauge_value_max' => NULL,
                'flow_temp_min' => NULL,
                'flow_temp_max' => NULL,
                'inlet_temp_min' => NULL,
                'inlet_temp_max' => '20',
                'stored_temp_min' => '0',
                'stored_temp_max' => '20',
                'top_temp_min' => NULL,
                'top_temp_max' => NULL,
                'bottom_temp_min' => NULL,
                'bottom_temp_max' => NULL,
                'return_temp_min' => NULL,
                'return_temp_max' => NULL,
            ),
        ));
        
        
    }
}