<?php

use Illuminate\Database\Seeder;

class CpValidateNonconformitiesTableSeedMasterSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('cp_validate_nonconformities')->delete();

        \DB::table('cp_validate_nonconformities')->insert(array (
            0 =>
            array (
                'id' => 1,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'operational_use',
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'state',
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'frequency_use',
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'source_condition',
                'nonconform_type' => 'Source Condition',
                'hazard_name' => 'Source Condition',
                'hazard_type' => '53',
                'answer_type' => 'dropdown',
                'value' => '82,83',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'source_accessibility',
                'nonconform_type' => 'Source Accessibility',
                'hazard_name' => 'Source Accessibility',
                'hazard_type' => '52',
                'answer_type' => 'dropdown',
                'value' => '77,78,79',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'insulation_type',
                'nonconform_type' => 'Insulation Type',
                'hazard_name' => 'Insulation Type',
                'hazard_type' => '34',
                'answer_type' => 'multi_select',
                'value' => '221',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'insulation_condition',
                'nonconform_type' => 'Insulation Condition',
                'hazard_name' => 'Insulation Condition',
                'hazard_type' => '32',
                'answer_type' => 'dropdown',
                'value' => '86,87,88',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'rodent_protection',
                'nonconform_type' => 'Rodent Protection',
                'hazard_name' => 'Rodent Protection',
                'hazard_type' => '48',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'tank_lid',
                'nonconform_type' => 'Tank Lid',
                'hazard_name' => 'Tank Lid',
                'hazard_type' => '56',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'air_vent',
                'nonconform_type' => 'Air Vent',
                'hazard_name' => 'Air Vent',
                'hazard_type' => '2',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'warning_pipe',
                'nonconform_type' => 'Overflow Warning',
                'hazard_name' => 'Overflow Warning',
                'hazard_type' => '61',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'can_isolated',
                'nonconform_type' => 'Can it be Isolated',
                'hazard_name' => 'Can it be Isolated',
                'hazard_type' => '7',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'main_access_hatch',
                'nonconform_type' => 'Main Access Hatch',
                'hazard_name' => 'Main Access Hatch',
                'hazard_type' => '37',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'ball_valve_hatch',
                'nonconform_type' => 'Separate Ball Valve Hatch',
                'hazard_name' => 'Separate Ball Valve Hatch',
                'hazard_type' => '49',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'envidence_stagnation',
                'nonconform_type' => 'Evidence of Stagnation',
                'hazard_name' => 'Evidence of Stagnation',
                'hazard_type' => '20',
                'answer_type' => 'dropdown',
                'value' => '209,210',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'degree_fouling',
                'nonconform_type' => 'Degree of Fouling',
                'hazard_name' => 'Degree of Fouling',
                'hazard_type' => '11',
                'answer_type' => 'dropdown',
                'value' => '95,96',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'degree_biological',
                'nonconform_type' => 'Degree of Biological Slime',
                'hazard_name' => 'Degree of Biological Slime',
                'hazard_type' => '10',
                'answer_type' => 'dropdown',
                'value' => '100,101',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'extent_corrosion',
                'nonconform_type' => 'Extent of Corrosion',
                'hazard_name' => 'Extent of Corrosion',
                'hazard_type' => '21',
                'answer_type' => 'dropdown',
                'value' => '105,106',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'cleanliness',
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'inlet_temp',
                'nonconform_type' => 'Inlet Temperature',
                'hazard_name' => 'Inlet Temperature',
                'hazard_type' => '31',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20',
            ),
            20 =>
            array (
                'id' => 21,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'stored_temp',
                'nonconform_type' => 'Stored Temperature',
                'hazard_name' => 'Stored Temperature',
                'hazard_type' => '55',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20',
            ),
            21 =>
            array (
                'id' => 22,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'ph',
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
            ),
            22 =>
            array (
                'id' => 23,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'operational_use',
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'state',
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'frequency_use',
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'insulation_type',
                'nonconform_type' => 'Insulation Type',
                'hazard_name' => 'Insulation Type',
                'hazard_type' => '34',
                'answer_type' => 'multi_select',
                'value' => '221',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'insulation_condition',
                'nonconform_type' => 'Insulation Condition',
                'hazard_name' => 'Insulation Condition',
                'hazard_type' => '32',
                'answer_type' => 'dropdown',
                'value' => '86,87,88',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'pipe_insulation',
                'nonconform_type' => 'Pipe Insulation',
                'hazard_name' => 'Pipe Insulation',
                'hazard_type' => '44',
                'answer_type' => 'multi_select',
                'value' => '222',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'pipe_insulation_condition',
                'nonconform_type' => 'Pipework Insulation Condition',
                'hazard_name' => 'Pipework Insulation Condition',
                'hazard_type' => '62',
                'answer_type' => 'dropdown',
                'value' => '203,204,205',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'anti_stratification',
                'nonconform_type' => 'Anti-stratification Pump Fitted',
                'hazard_name' => 'Anti-stratification Pump Fitted',
                'hazard_type' => '3',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'direct_fired',
                'nonconform_type' => 'Direct/Indirect Fired',
                'hazard_name' => 'Direct/Indirect Fired',
                'hazard_type' => '12',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'drain_valve',
                'nonconform_type' => 'Drain Valve',
                'hazard_name' => 'Drain Valve',
                'hazard_type' => '13',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            32 =>
            array (
                'id' => 33,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'cleanliness',
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'stored_temp',
                'nonconform_type' => 'Storage Temperature',
                'hazard_name' => 'Storage Temperature',
                'hazard_type' => '54',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '60',
                'value_min' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'flow_temp',
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'return_temp',
                'nonconform_type' => 'Return Temperature',
                'hazard_name' => 'Return Temperature',
                'hazard_type' => '46',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '45',
                'value_min' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'flow_temp_gauge_value',
                'nonconform_type' => 'Flow Temperature Gauge',
                'hazard_name' => 'Flow Temperature Gauge',
                'hazard_type' => '23',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
            ),
            37 =>
            array (
                'id' => 38,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'return_temp_gauge_value',
                'nonconform_type' => 'Return Temperature Gauge',
                'hazard_name' => 'Return Temperature Gauge',
                'hazard_type' => '47',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '45',
                'value_min' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'ph',
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
            ),
            39 =>
            array (
                'id' => 40,
                'tmv' => null,
                'template_id' => 7,
                'field' => 'operational_use',
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            40 =>
            array (
                'id' => 41,
                'tmv' => null,
                'template_id' => 7,
                'field' => 'state',
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'tmv' => null,
                'template_id' => 7,
                'field' => 'frequency_use',
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            42 =>
            array (
                'id' => 43,
                'tmv' => null,
                'template_id' => 7,
                'field' => 'aerosol_risk',
                'nonconform_type' => 'Aerosol Risk',
                'hazard_name' => 'Aerosol Risk',
                'hazard_type' => '1',
                'answer_type' => 'dropdown',
                'value' => '199,200',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            43 =>
            array (
                'id' => 44,
                'tmv' => null,
                'template_id' => 7,
                'field' => 'pipe_insulation',
                'nonconform_type' => 'Pipe Insulation',
                'hazard_name' => 'Pipe Insulation',
                'hazard_type' => '44',
                'answer_type' => 'multi_select',
                'value' => '222',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            44 =>
            array (
                'id' => 45,
                'tmv' => null,
                'template_id' => 7,
                'field' => 'pipe_insulation_condition',
                'nonconform_type' => 'Pipework Insulation Condition',
                'hazard_name' => 'Pipework Insulation Condition',
                'hazard_type' => '62',
                'answer_type' => 'dropdown',
                'value' => '203,204,205',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            45 =>
            array (
                'id' => 46,
                'tmv' => null,
                'template_id' => 7,
                'field' => 'cleanliness',
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            46 =>
            array (
                'id' => 47,
                'tmv' => null,
                'template_id' => 7,
                'field' => 'flow_temp',
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
            ),
            47 =>
            array (
                'id' => 48,
                'tmv' => null,
                'template_id' => 7,
                'field' => 'ph',
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
            ),
            48 =>
            array (
                'id' => 49,
                'tmv' => null,
                'template_id' => 6,
                'field' => 'operational_use',
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            49 =>
            array (
                'id' => 50,
                'tmv' => null,
                'template_id' => 6,
                'field' => 'state',
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            50 =>
            array (
                'id' => 51,
                'tmv' => null,
                'template_id' => 6,
                'field' => 'frequency_use',
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            51 =>
            array (
                'id' => 52,
                'tmv' => null,
                'template_id' => 6,
                'field' => 'aerosol_risk',
                'nonconform_type' => 'Aerosol Risk',
                'hazard_name' => 'Aerosol Risk',
                'hazard_type' => '1',
                'answer_type' => 'dropdown',
                'value' => '199,200',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            52 =>
            array (
                'id' => 53,
                'tmv' => null,
                'template_id' => 6,
                'field' => 'pipe_insulation',
                'nonconform_type' => 'Pipe Insulation',
                'hazard_name' => 'Pipe Insulation',
                'hazard_type' => '44',
                'answer_type' => 'multi_select',
                'value' => '222',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            53 =>
            array (
                'id' => 54,
                'tmv' => null,
                'template_id' => 6,
                'field' => 'pipe_insulation_condition',
                'nonconform_type' => 'Pipework Insulation Condition',
                'hazard_name' => 'Pipework Insulation Condition',
                'hazard_type' => '62',
                'answer_type' => 'dropdown',
                'value' => '203,204,205',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            54 =>
            array (
                'id' => 55,
                'tmv' => null,
                'template_id' => 6,
                'field' => 'cleanliness',
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            55 =>
            array (
                'id' => 56,
                'tmv' => 0,
                'template_id' => 6,
                'field' => 'flow_temp',
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => null,
            ),
            56 =>
            array (
                'id' => 57,
                'tmv' => null,
                'template_id' => 6,
                'field' => 'ph',
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
            ),
            57 =>
            array (
                'id' => 58,
                'tmv' => null,
                'template_id' => 4,
                'field' => 'operational_use',
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            58 =>
            array (
                'id' => 59,
                'tmv' => null,
                'template_id' => 4,
                'field' => 'state',
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            59 =>
            array (
                'id' => 60,
                'tmv' => null,
                'template_id' => 4,
                'field' => 'frequency_use',
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            60 =>
            array (
                'id' => 61,
                'tmv' => null,
                'template_id' => 4,
                'field' => 'aerosol_risk',
                'nonconform_type' => 'Aerosol Risk',
                'hazard_name' => 'Aerosol Risk',
                'hazard_type' => '1',
                'answer_type' => 'dropdown',
                'value' => '199,200',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            61 =>
            array (
                'id' => 62,
                'tmv' => null,
                'template_id' => 4,
                'field' => 'cleanliness',
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            62 =>
            array (
                'id' => 63,
                'tmv' => null,
                'template_id' => 4,
                'field' => 'flow_temp',
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '19',
            ),
            63 =>
            array (
                'id' => 64,
                'tmv' => null,
                'template_id' => 4,
                'field' => 'ph',
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
            ),
            64 =>
            array (
                'id' => 65,
                'tmv' => null,
                'template_id' => 5,
                'field' => 'operational_use',
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            65 =>
            array (
                'id' => 66,
                'tmv' => null,
                'template_id' => 5,
                'field' => 'state',
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            66 =>
            array (
                'id' => 67,
                'tmv' => null,
                'template_id' => 5,
                'field' => 'frequency_use',
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            67 =>
            array (
                'id' => 68,
                'tmv' => null,
                'template_id' => 5,
                'field' => 'aerosol_risk',
                'nonconform_type' => 'Aerosol Risk',
                'hazard_name' => 'Aerosol Risk',
                'hazard_type' => '1',
                'answer_type' => 'dropdown',
                'value' => '199,200',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            68 =>
            array (
                'id' => 69,
                'tmv' => null,
                'template_id' => 5,
                'field' => 'pipe_insulation',
                'nonconform_type' => 'Pipe Insulation',
                'hazard_name' => 'Pipe Insulation',
                'hazard_type' => '44',
                'answer_type' => 'multi_select',
                'value' => '222',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            69 =>
            array (
                'id' => 70,
                'tmv' => null,
                'template_id' => 5,
                'field' => 'pipe_insulation_condition',
                'nonconform_type' => 'Pipework Insulation Condition',
                'hazard_name' => 'Pipework Insulation Condition',
                'hazard_type' => '62',
                'answer_type' => 'dropdown',
                'value' => '203,204,205',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            70 =>
            array (
                'id' => 71,
                'tmv' => null,
                'template_id' => 5,
                'field' => 'cleanliness',
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            71 =>
            array (
                'id' => 72,
                'tmv' => 0,
                'template_id' => 5,
                'field' => 'top_temp',
                'nonconform_type' => 'Top Temperature',
                'hazard_name' => 'Top Temperature',
                'hazard_type' => '58',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => null,
            ),
            72 =>
            array (
                'id' => 73,
                'tmv' => 0,
                'template_id' => 5,
                'field' => 'bottom_temp',
                'nonconform_type' => 'Bottom Temperature',
                'hazard_name' => 'Bottom Temperature',
                'hazard_type' => '63',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '20',
                'value_min' => NULL
            ),
            73 =>
            array (
                'id' => 74,
                'tmv' => null,
                'template_id' => 5,
                'field' => 'ph',
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
            ),
            74 =>
            array (
                'id' => 75,
                'tmv' => null,
                'template_id' => 1,
                'field' => 'operational_use',
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            75 =>
            array (
                'id' => 76,
                'tmv' => null,
                'template_id' => 1,
                'field' => 'state',
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            76 =>
            array (
                'id' => 77,
                'tmv' => null,
                'template_id' => 1,
                'field' => 'frequency_use',
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            77 =>
            array (
                'id' => 78,
                'tmv' => null,
                'template_id' => 1,
                'field' => 'cleanliness',
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            78 =>
            array (
                'id' => 79,
                'tmv' => null,
                'template_id' => 2,
                'field' => 'backflow_protection',
                'nonconform_type' => 'Backflow Protection',
                'hazard_name' => 'Backflow Protection',
                'hazard_type' => '65',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            79 =>
            array (
                'id' => 80,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'screened_lid_vent',
                'nonconform_type' => 'Screened Lid Vent',
                'hazard_name' => 'Screened Lid Vent',
                'hazard_type' => '56',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            80 =>
            array (
                'id' => 81,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'overflow_pipe',
                'nonconform_type' => 'Overflow Pipe',
                'hazard_name' => 'Overflow Pipe',
                'hazard_type' => '64',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            81 =>
            array (
                'id' => 82,
                'tmv' => null,
                'template_id' => 3,
                'field' => 'backflow_protection',
                'nonconform_type' => 'Backflow Protection',
                'hazard_name' => 'Backflow Protection',
                'hazard_type' => '65',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            // 82 =>
            // array (
            //     'id' => 83,
            //     'template_id' => 3,
            //     'field' => 'ball_valve_hatch',
            //     'nonconform_type' => 'Separate Ball Valve Hatch',
            //     'hazard_name' => 'Separate Ball Valve Hatch',
            //     'hazard_type' => '49',
            //     'answer_type' => 'boolean',
            //     'value' => '0',
            //     'value_max' => NULL,
            //     'value_min' => NULL,
            // ),
            83 =>
            array (
                'id' => 84,
                'tmv' => 1,
                'template_id' => 6,
                'field' => 'flow_temp',
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '39',
                'value_min' => '43',
            ),
            84 =>
            array (
                'id' => 85,
                'tmv' => 1,
                'template_id' => 5,
                'field' => 'top_temp',
                'nonconform_type' => 'Top Temperature',
                'hazard_name' => 'Top Temperature',
                'hazard_type' => '58',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '39',
                'value_min' => '43',
            ),
            85 =>
            array (
                'id' => 86,
                'tmv' => null,
                'template_id' => 1,
                'field' => 'type',
            'nonconform_type' => 'Dead End (<6 Pipe Diameter)',
                'hazard_name' => 'Miscellaneous',
                'hazard_type' => '69',
                'answer_type' => 'dropdown',
                'value' => '34',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            86 =>
            array (
                'id' => 87,
                'tmv' => null,
                'template_id' => 1,
                'field' => 'type',
            'nonconform_type' => 'Dead End (6+ Pipe Diameter)',
                'hazard_name' => 'Miscellaneous',
                'hazard_type' => '70',
                'answer_type' => 'dropdown',
                'value' => '35',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            87 =>
            array (
                'id' => 88,
                'tmv' => null,
                'template_id' => 1,
                'field' => 'type',
                'nonconform_type' => 'Dead Leg',
                'hazard_name' => 'Miscellaneous',
                'hazard_type' => '71',
                'answer_type' => 'dropdown',
                'value' => '36',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            88 =>
            array (
                'id' => 89,
                'tmv' => null,
                'template_id' => 8,
                'field' => 'operational_use',
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            89 =>
            array (
                'id' => 90,
                'tmv' => null,
                'template_id' => 8,
                'field' => 'state',
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            90 =>
            array (
                'id' => 91,
                'tmv' => null,
                'template_id' => 8,
                'field' => 'frequency_use',
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            91 =>
            array (
                'id' => 92,
                'tmv' => null,
                'template_id' => 8,
                'field' => 'condition_of_pipework',
                'nonconform_type' => 'Pipework Condition',
                'hazard_name' => 'Pipework Condition',
                'hazard_type' => '72',
                'answer_type' => 'dropdown',
                'value' => '86,87,88',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            92 =>
            array (
                'id' => 93,
                'tmv' => null,
                'template_id' => 8,
                'field' => 'insulation_condition',
                'nonconform_type' => 'Insulation Condition',
                'hazard_name' => 'Insulation Condition',
                'hazard_type' => '32',
                'answer_type' => 'dropdown',
                'value' => '86,87,88',
                'value_max' => NULL,
                'value_min' => NULL,
            ),
            93 =>
            array (
                'id' => 94,
                'tmv' => null,
                'template_id' => 8,
                'field' => 'incoming_main_pipe_work_temp',
                'nonconform_type' => 'Incoming Mains Pipework Temperature',
                'hazard_name' => 'Incoming Mains Pipework Temperature',
                'hazard_type' => '73',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20',
            ),
            94 =>
            array (
                'id' => 95,
                'tmv' => 1,
                'template_id' => 5,
                'field' => 'bottom_temp',
                'nonconform_type' => 'Bottom Temperature',
                'hazard_name' => 'Bottom Temperature',
                'hazard_type' => '63',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20'
            ),
        ));


    }
}
