<?php

use Illuminate\Database\Seeder;

class CpValidateNonconformitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('cp_validate_nonconformities')->delete();

        \DB::table('cp_validate_nonconformities')->insert(array (
            0 =>
            array (
                'id' => 1,
                'template_id' => 3,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            1 =>
            array (
                'id' => 2,
                'template_id' => 3,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            2 =>
            array (
                'id' => 3,
                'template_id' => 3,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            3 =>
            array (
                'id' => 4,
                'template_id' => 3,
                'field' => 'source_condition',
                'tmv' => NULL,
                'nonconform_type' => 'Source Condition',
                'hazard_name' => 'Source Condition',
                'hazard_type' => '53',
                'answer_type' => 'dropdown',
                'value' => '82,83',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            4 =>
            array (
                'id' => 5,
                'template_id' => 3,
                'field' => 'source_accessibility',
                'tmv' => NULL,
                'nonconform_type' => 'Source Accessibility',
                'hazard_name' => 'Source Accessibility',
                'hazard_type' => '52',
                'answer_type' => 'dropdown',
                'value' => '77,78,79',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            5 =>
            array (
                'id' => 6,
                'template_id' => 3,
                'field' => 'insulation_type',
                'tmv' => NULL,
                'nonconform_type' => 'Insulation Type',
                'hazard_name' => 'Insulation Type',
                'hazard_type' => '34',
                'answer_type' => 'multi_select',
                'value' => '221',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            6 =>
            array (
                'id' => 7,
                'template_id' => 3,
                'field' => 'insulation_condition',
                'tmv' => NULL,
                'nonconform_type' => 'Insulation Condition',
                'hazard_name' => 'Insulation Condition',
                'hazard_type' => '32',
                'answer_type' => 'dropdown',
                'value' => '86,87,88',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            7 =>
            array (
                'id' => 8,
                'template_id' => 3,
                'field' => 'rodent_protection',
                'tmv' => NULL,
                'nonconform_type' => 'Rodent Protection',
                'hazard_name' => 'Rodent Protection',
                'hazard_type' => '48',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            8 =>
            array (
                'id' => 9,
                'template_id' => 3,
                'field' => 'tank_lid',
                'tmv' => NULL,
                'nonconform_type' => 'Tank Lid',
                'hazard_name' => 'Tank Lid',
                'hazard_type' => '56',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            9 =>
            array (
                'id' => 10,
                'template_id' => 3,
                'field' => 'air_vent',
                'tmv' => NULL,
                'nonconform_type' => 'Air Vent',
                'hazard_name' => 'Air Vent',
                'hazard_type' => '2',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            10 =>
            array (
                'id' => 11,
                'template_id' => 3,
                'field' => 'warning_pipe',
                'tmv' => NULL,
                'nonconform_type' => 'Overflow Warning',
                'hazard_name' => 'Overflow Warning',
                'hazard_type' => '61',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            11 =>
            array (
                'id' => 12,
                'template_id' => 3,
                'field' => 'can_isolated',
                'tmv' => NULL,
                'nonconform_type' => 'Can it be Isolated',
                'hazard_name' => 'Can it be Isolated',
                'hazard_type' => '7',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            12 =>
            array (
                'id' => 13,
                'template_id' => 3,
                'field' => 'main_access_hatch',
                'tmv' => NULL,
                'nonconform_type' => 'Main Access Hatch',
                'hazard_name' => 'Main Access Hatch',
                'hazard_type' => '37',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            13 =>
            array (
                'id' => 14,
                'template_id' => 3,
                'field' => 'ball_valve_hatch',
                'tmv' => NULL,
                'nonconform_type' => 'Separate Ball Valve Hatch',
                'hazard_name' => 'Separate Ball Valve Hatch',
                'hazard_type' => '49',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            14 =>
            array (
                'id' => 15,
                'template_id' => 3,
                'field' => 'envidence_stagnation',
                'tmv' => NULL,
                'nonconform_type' => 'Evidence of Stagnation',
                'hazard_name' => 'Evidence of Stagnation',
                'hazard_type' => '20',
                'answer_type' => 'dropdown',
                'value' => '209,210',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            15 =>
            array (
                'id' => 16,
                'template_id' => 3,
                'field' => 'degree_fouling',
                'tmv' => NULL,
                'nonconform_type' => 'Degree of Fouling',
                'hazard_name' => 'Degree of Fouling',
                'hazard_type' => '11',
                'answer_type' => 'dropdown',
                'value' => '95,96',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            16 =>
            array (
                'id' => 17,
                'template_id' => 3,
                'field' => 'degree_biological',
                'tmv' => NULL,
                'nonconform_type' => 'Degree of Biological Slime',
                'hazard_name' => 'Degree of Biological Slime',
                'hazard_type' => '10',
                'answer_type' => 'dropdown',
                'value' => '100,101',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            17 =>
            array (
                'id' => 18,
                'template_id' => 3,
                'field' => 'extent_corrosion',
                'tmv' => NULL,
                'nonconform_type' => 'Extent of Corrosion',
                'hazard_name' => 'Extent of Corrosion',
                'hazard_type' => '21',
                'answer_type' => 'dropdown',
                'value' => '105,106',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            18 =>
            array (
                'id' => 19,
                'template_id' => 3,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            19 =>
            array (
                'id' => 20,
                'template_id' => 3,
                'field' => 'inlet_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Inlet Temperature',
                'hazard_name' => 'Inlet Temperature',
                'hazard_type' => '31',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20',
                'check_equal' => 1,
            ),
            20 =>
            array (
                'id' => 21,
                'template_id' => 3,
                'field' => 'stored_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Stored Temperature',
                'hazard_name' => 'Stored Temperature',
                'hazard_type' => '55',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20',
                'check_equal' => 1,
            ),
            21 =>
            array (
                'id' => 22,
                'template_id' => 3,
                'field' => 'ph',
                'tmv' => NULL,
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
                'check_equal' => 1,
            ),
            22 =>
            array (
                'id' => 23,
                'template_id' => 2,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            23 =>
            array (
                'id' => 24,
                'template_id' => 2,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            24 =>
            array (
                'id' => 25,
                'template_id' => 2,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            25 =>
            array (
                'id' => 26,
                'template_id' => 2,
                'field' => 'insulation_type',
                'tmv' => NULL,
                'nonconform_type' => 'Insulation Type',
                'hazard_name' => 'Insulation Type',
                'hazard_type' => '34',
                'answer_type' => 'multi_select',
                'value' => '221',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            26 =>
            array (
                'id' => 27,
                'template_id' => 2,
                'field' => 'insulation_condition',
                'tmv' => NULL,
                'nonconform_type' => 'Insulation Condition',
                'hazard_name' => 'Insulation Condition',
                'hazard_type' => '32',
                'answer_type' => 'dropdown',
                'value' => '86,87,88',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            27 =>
            array (
                'id' => 28,
                'template_id' => 2,
                'field' => 'pipe_insulation',
                'tmv' => NULL,
                'nonconform_type' => 'Pipe Insulation',
                'hazard_name' => 'Pipe Insulation',
                'hazard_type' => '44',
                'answer_type' => 'multi_select',
                'value' => '222',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            28 =>
            array (
                'id' => 29,
                'template_id' => 2,
                'field' => 'pipe_insulation_condition',
                'tmv' => NULL,
                'nonconform_type' => 'Pipework Insulation Condition',
                'hazard_name' => 'Pipework Insulation Condition',
                'hazard_type' => '62',
                'answer_type' => 'dropdown',
                'value' => '203,204,205',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            29 =>
            array (
                'id' => 30,
                'template_id' => 2,
                'field' => 'anti_stratification',
                'tmv' => NULL,
                'nonconform_type' => 'Anti-stratification Pump Fitted',
                'hazard_name' => 'Anti-stratification Pump Fitted',
                'hazard_type' => '3',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            30 =>
            array (
                'id' => 32,
                'template_id' => 2,
                'field' => 'drain_valve',
                'tmv' => NULL,
                'nonconform_type' => 'Drain Valve',
                'hazard_name' => 'Drain Valve',
                'hazard_type' => '13',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            31 =>
            array (
                'id' => 33,
                'template_id' => 2,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            32 =>
            array (
                'id' => 34,
                'template_id' => 2,
                'field' => 'stored_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Storage Temperature',
                'hazard_name' => 'Storage Temperature',
                'hazard_type' => '54',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '60',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            33 =>
            array (
                'id' => 35,
                'template_id' => 2,
                'field' => 'flow_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            34 =>
            array (
                'id' => 36,
                'template_id' => 2,
                'field' => 'return_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Return Temperature',
                'hazard_name' => 'Return Temperature',
                'hazard_type' => '46',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '45',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            35 =>
            array (
                'id' => 37,
                'template_id' => 2,
                'field' => 'flow_temp_gauge_value',
                'tmv' => NULL,
                'nonconform_type' => 'Flow Temperature Gauge',
                'hazard_name' => 'Flow Temperature Gauge',
                'hazard_type' => '23',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            36 =>
            array (
                'id' => 38,
                'template_id' => 2,
                'field' => 'return_temp_gauge_value',
                'tmv' => NULL,
                'nonconform_type' => 'Return Temperature Gauge',
                'hazard_name' => 'Return Temperature Gauge',
                'hazard_type' => '47',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '45',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            37 =>
            array (
                'id' => 39,
                'template_id' => 2,
                'field' => 'ph',
                'tmv' => NULL,
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
                'check_equal' => 1,
            ),
            38 =>
            array (
                'id' => 40,
                'template_id' => 7,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            39 =>
            array (
                'id' => 41,
                'template_id' => 7,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            40 =>
            array (
                'id' => 42,
                'template_id' => 7,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            // 41 =>
            // array (
            //     'id' => 43,
            //     'template_id' => 7,
            //     'field' => 'aerosol_risk',
            //     'tmv' => NULL,
            //     'nonconform_type' => 'Aerosol Risk',
            //     'hazard_name' => 'Aerosol Risk',
            //     'hazard_type' => '1',
            //     'answer_type' => 'dropdown',
            //     'value' => '199,200',
            //     'value_max' => NULL,
            //     'value_min' => NULL,
            //     'check_equal' => 0,
            // ),
            42 =>
            array (
                'id' => 44,
                'template_id' => 7,
                'field' => 'pipe_insulation',
                'tmv' => NULL,
                'nonconform_type' => 'Pipe Insulation',
                'hazard_name' => 'Pipe Insulation',
                'hazard_type' => '44',
                'answer_type' => 'multi_select',
                'value' => '222',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            43 =>
            array (
                'id' => 45,
                'template_id' => 7,
                'field' => 'pipe_insulation_condition',
                'tmv' => NULL,
                'nonconform_type' => 'Pipework Insulation Condition',
                'hazard_name' => 'Pipework Insulation Condition',
                'hazard_type' => '62',
                'answer_type' => 'dropdown',
                'value' => '203,204,205',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            44 =>
            array (
                'id' => 46,
                'template_id' => 7,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            45 =>
            array (
                'id' => 47,
                'template_id' => 7,
                'field' => 'flow_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            46 =>
            array (
                'id' => 48,
                'template_id' => 7,
                'field' => 'ph',
                'tmv' => NULL,
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
                'check_equal' => 1,
            ),
            47 =>
            array (
                'id' => 49,
                'template_id' => 6,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            48 =>
            array (
                'id' => 50,
                'template_id' => 6,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            49 =>
            array (
                'id' => 51,
                'template_id' => 6,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            // 50 =>
            // array (
            //     'id' => 52,
            //     'template_id' => 6,
            //     'field' => 'aerosol_risk',
            //     'tmv' => NULL,
            //     'nonconform_type' => 'Aerosol Risk',
            //     'hazard_name' => 'Aerosol Risk',
            //     'hazard_type' => '1',
            //     'answer_type' => 'dropdown',
            //     'value' => '199,200',
            //     'value_max' => NULL,
            //     'value_min' => NULL,
            //     'check_equal' => 0,
            // ),
            51 =>
            array (
                'id' => 53,
                'template_id' => 6,
                'field' => 'pipe_insulation',
                'tmv' => NULL,
                'nonconform_type' => 'Pipe Insulation',
                'hazard_name' => 'Pipe Insulation',
                'hazard_type' => '44',
                'answer_type' => 'multi_select',
                'value' => '222',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            52 =>
            array (
                'id' => 54,
                'template_id' => 6,
                'field' => 'pipe_insulation_condition',
                'tmv' => NULL,
                'nonconform_type' => 'Pipework Insulation Condition',
                'hazard_name' => 'Pipework Insulation Condition',
                'hazard_type' => '62',
                'answer_type' => 'dropdown',
                'value' => '203,204,205',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            53 =>
            array (
                'id' => 55,
                'template_id' => 6,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            54 =>
            array (
                'id' => 56,
                'template_id' => 6,
                'field' => 'flow_temp',
                'tmv' => 0,
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            55 =>
            array (
                'id' => 57,
                'template_id' => 6,
                'field' => 'ph',
                'tmv' => 0,
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
                'check_equal' => 1,
            ),
            56 =>
            array (
                'id' => 58,
                'template_id' => 4,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            57 =>
            array (
                'id' => 59,
                'template_id' => 4,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            58 =>
            array (
                'id' => 60,
                'template_id' => 4,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            // 59 =>
            // array (
            //     'id' => 61,
            //     'template_id' => 4,
            //     'field' => 'aerosol_risk',
            //     'tmv' => NULL,
            //     'nonconform_type' => 'Aerosol Risk',
            //     'hazard_name' => 'Aerosol Risk',
            //     'hazard_type' => '1',
            //     'answer_type' => 'dropdown',
            //     'value' => '199,200',
            //     'value_max' => NULL,
            //     'value_min' => NULL,
            //     'check_equal' => 0,
            // ),
            60 =>
            array (
                'id' => 62,
                'template_id' => 4,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            61 =>
            array (
                'id' => 63,
                'template_id' => 4,
                'field' => 'flow_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20',
                'check_equal' => 1,
            ),
            62 =>
            array (
                'id' => 64,
                'template_id' => 4,
                'field' => 'ph',
                'tmv' => NULL,
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
                'check_equal' => 1,
            ),
            63 =>
            array (
                'id' => 65,
                'template_id' => 5,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            64 =>
            array (
                'id' => 66,
                'template_id' => 5,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            65 =>
            array (
                'id' => 67,
                'template_id' => 5,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            // 66 =>
            // array (
            //     'id' => 68,
            //     'template_id' => 5,
            //     'field' => 'aerosol_risk',
            //     'tmv' => NULL,
            //     'nonconform_type' => 'Aerosol Risk',
            //     'hazard_name' => 'Aerosol Risk',
            //     'hazard_type' => '1',
            //     'answer_type' => 'dropdown',
            //     'value' => '199,200',
            //     'value_max' => NULL,
            //     'value_min' => NULL,
            //     'check_equal' => 0,
            // ),
            67 =>
            array (
                'id' => 69,
                'template_id' => 5,
                'field' => 'pipe_insulation',
                'tmv' => NULL,
                'nonconform_type' => 'Pipe Insulation',
                'hazard_name' => 'Pipe Insulation',
                'hazard_type' => '44',
                'answer_type' => 'multi_select',
                'value' => '222',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            68 =>
            array (
                'id' => 70,
                'template_id' => 5,
                'field' => 'pipe_insulation_condition',
                'tmv' => NULL,
                'nonconform_type' => 'Pipework Insulation Condition',
                'hazard_name' => 'Pipework Insulation Condition',
                'hazard_type' => '62',
                'answer_type' => 'dropdown',
                'value' => '203,204,205',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            69 =>
            array (
                'id' => 71,
                'template_id' => 5,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            70 =>
            array (
                'id' => 72,
                'template_id' => 5,
                'field' => 'top_temp',
                'tmv' => 0,
                'nonconform_type' => 'Top Temperature',
                'hazard_name' => 'Top Temperature',
                'hazard_type' => '58',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            71 =>
            array (
                'id' => 73,
                'template_id' => 5,
                'field' => 'bottom_temp',
                'tmv' => 0,
                'nonconform_type' => 'Bottom Temperature',
                'hazard_name' => 'Bottom Temperature',
                'hazard_type' => '63',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20',
                'check_equal' => 1,
            ),
            72 =>
            array (
                'id' => 74,
                'template_id' => 5,
                'field' => 'ph',
                'tmv' => NULL,
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
                'check_equal' => 1,
            ),
            73 =>
            array (
                'id' => 75,
                'template_id' => 1,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            74 =>
            array (
                'id' => 76,
                'template_id' => 1,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            75 =>
            array (
                'id' => 77,
                'template_id' => 1,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            76 =>
            array (
                'id' => 78,
                'template_id' => 1,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            77 =>
            array (
                'id' => 79,
                'template_id' => 2,
                'field' => 'backflow_protection',
                'tmv' => NULL,
                'nonconform_type' => 'Backflow Protection',
                'hazard_name' => 'Backflow Protection',
                'hazard_type' => '65',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            78 =>
            array (
                'id' => 80,
                'template_id' => 3,
                'field' => 'screened_lid_vent',
                'tmv' => NULL,
                'nonconform_type' => 'Screened Lid Vent',
                'hazard_name' => 'Screened Lid Vent',
                'hazard_type' => '56',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            79 =>
            array (
                'id' => 81,
                'template_id' => 3,
                'field' => 'overflow_pipe',
                'tmv' => NULL,
                'nonconform_type' => 'Overflow Pipe',
                'hazard_name' => 'Overflow Pipe',
                'hazard_type' => '64',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            80 =>
            array (
                'id' => 82,
                'template_id' => 3,
                'field' => 'backflow_protection',
                'tmv' => NULL,
                'nonconform_type' => 'Backflow Protection',
                'hazard_name' => 'Backflow Protection',
                'hazard_type' => '65',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            81 =>
            array (
                'id' => 84,
                'template_id' => 6,
                'field' => 'flow_temp',
                'tmv' => 1,
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '39',
                'value_min' => '43',
                'check_equal' => 0,
            ),
            82 =>
            array (
                'id' => 85,
                'template_id' => 5,
                'field' => 'top_temp',
                'tmv' => 1,
                'nonconform_type' => 'Top Temperature',
                'hazard_name' => 'Top Temperature',
                'hazard_type' => '58',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '39',
                'value_min' => '43',
                'check_equal' => 0,
            ),
            83 =>
            array (
                'id' => 86,
                'template_id' => 1,
                'field' => 'type',
                'tmv' => NULL,
            'nonconform_type' => 'Dead End (<6 Pipe Diameter)',
                'hazard_name' => 'Miscellaneous',
                'hazard_type' => '69',
                'answer_type' => 'dropdown',
                'value' => '34',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            84 =>
            array (
                'id' => 87,
                'template_id' => 1,
                'field' => 'type',
                'tmv' => NULL,
            'nonconform_type' => 'Dead End (6+ Pipe Diameter)',
                'hazard_name' => 'Miscellaneous',
                'hazard_type' => '70',
                'answer_type' => 'dropdown',
                'value' => '35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            85 =>
            array (
                'id' => 88,
                'template_id' => 1,
                'field' => 'type',
                'tmv' => NULL,
                'nonconform_type' => 'Dead Leg',
                'hazard_name' => 'Miscellaneous',
                'hazard_type' => '71',
                'answer_type' => 'dropdown',
                'value' => '36',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            86 =>
            array (
                'id' => 89,
                'template_id' => 8,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            87 =>
            array (
                'id' => 90,
                'template_id' => 8,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            88 =>
            array (
                'id' => 91,
                'template_id' => 8,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            89 =>
            array (
                'id' => 92,
                'template_id' => 8,
                'field' => 'condition_of_pipework',
                'tmv' => NULL,
                'nonconform_type' => 'Pipework Condition',
                'hazard_name' => 'Pipework Condition',
                'hazard_type' => '72',
                'answer_type' => 'dropdown',
                'value' => '86,87,88',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            90 =>
            array (
                'id' => 93,
                'template_id' => 8,
                'field' => 'insulation_condition',
                'tmv' => NULL,
                'nonconform_type' => 'Insulation Condition',
                'hazard_name' => 'Insulation Condition',
                'hazard_type' => '32',
                'answer_type' => 'dropdown',
                'value' => '86,87,88',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            91 =>
            array (
                'id' => 94,
                'template_id' => 8,
                'field' => 'incoming_main_pipe_work_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Incoming Mains Pipework Temperature',
                'hazard_name' => 'Incoming Mains Pipework Temperature',
                'hazard_type' => '73',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20',
                'check_equal' => 1,
            ),
            92 =>
            array (
                'id' => 95,
                'template_id' => 5,
                'field' => 'bottom_tempinsulation_condition',
                'tmv' => 1,
                'nonconform_type' => 'Bottom Temperature',
                'hazard_name' => 'Bottom Temperature',
                'hazard_type' => '63',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20',
                'check_equal' => 1,
            ),
            93 =>
            array (
                'id' => 96,
                'template_id' => 3,
                'field' => 'insulation_thickness',
                'tmv' => 0,
                'nonconform_type' => 'Insulation Thickness',
                'hazard_name' => 'Insulation Thickness',
                'hazard_type' => '33',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            94 =>
            array (
                'id' => 97,
                'template_id' => 2,
                'field' => 'insulation_thickness',
                'tmv' => 0,
                'nonconform_type' => 'Insulation Thickness',
                'hazard_name' => 'Insulation Thickness',
                'hazard_type' => '33',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            95 =>
            array (
                'id' => 98,
                'template_id' => 10,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            96 =>
            array (
                'id' => 99,
                'template_id' => 10,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            97 =>
            array (
                'id' => 100,
                'template_id' => 10,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            98 =>
            array (
                'id' => 101,
                'template_id' => 10,
                'field' => 'flow_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            99 =>
            array (
                'id' => 102,
                'template_id' => 11,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            100 =>
            array (
                'id' => 103,
                'template_id' => 11,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            101 =>
            array (
                'id' => 104,
                'template_id' => 11,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            102 =>
            array (
                'id' => 105,
                'template_id' => 11,
                'field' => 'insulation_type',
                'tmv' => NULL,
                'nonconform_type' => 'Insulation Type',
                'hazard_name' => 'Insulation Type',
                'hazard_type' => '34',
                'answer_type' => 'multi_select',
                'value' => '221',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            103 =>
            array (
                'id' => 106,
                'template_id' => 11,
                'field' => 'insulation_condition',
                'tmv' => NULL,
                'nonconform_type' => 'Insulation Condition',
                'hazard_name' => 'Insulation Condition',
                'hazard_type' => '32',
                'answer_type' => 'dropdown',
                'value' => '86,87,88',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            104 =>
            array (
                'id' => 107,
                'template_id' => 11,
                'field' => 'pipe_insulation',
                'tmv' => NULL,
                'nonconform_type' => 'Pipe Insulation',
                'hazard_name' => 'Pipe Insulation',
                'hazard_type' => '44',
                'answer_type' => 'multi_select',
                'value' => '222',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            105 =>
            array (
                'id' => 108,
                'template_id' => 11,
                'field' => 'pipe_insulation_condition',
                'tmv' => NULL,
                'nonconform_type' => 'Pipework Insulation Condition',
                'hazard_name' => 'Pipework Insulation Condition',
                'hazard_type' => '62',
                'answer_type' => 'dropdown',
                'value' => '203,204,205',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            // 106 =>
            // array (
            //     'id' => 110,
            //     'template_id' => 11,
            //     'field' => 'direct_fired',
            //     'tmv' => NULL,
            //     'nonconform_type' => 'Direct/Indirect Fired',
            //     'hazard_name' => 'Direct/Indirect Fired',
            //     'hazard_type' => '12',
            //     'answer_type' => 'boolean',
            //     'value' => '0',
            //     'value_max' => NULL,
            //     'value_min' => NULL,
            //     'check_equal' => 0,
            // ),
            107 =>
            array (
                'id' => 111,
                'template_id' => 11,
                'field' => 'drain_valve',
                'tmv' => NULL,
                'nonconform_type' => 'Drain Valve',
                'hazard_name' => 'Drain Valve',
                'hazard_type' => '13',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            108 =>
            array (
                'id' => 112,
                'template_id' => 11,
                'field' => 'backflow_protection',
                'tmv' => NULL,
                'nonconform_type' => 'Backflow Protection',
                'hazard_name' => 'Backflow Protection',
                'hazard_type' => '65',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            109 =>
            array (
                'id' => 113,
                'template_id' => 11,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            110 =>
            array (
                'id' => 114,
                'template_id' => 11,
                'field' => 'stored_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Storage Temperature',
                'hazard_name' => 'Storage Temperature',
                'hazard_type' => '54',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '60',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            111 =>
            array (
                'id' => 115,
                'template_id' => 11,
                'field' => 'flow_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            112 =>
            array (
                'id' => 116,
                'template_id' => 11,
                'field' => 'return_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Return Temperature',
                'hazard_name' => 'Return Temperature',
                'hazard_type' => '46',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '45',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            113 =>
            array (
                'id' => 117,
                'template_id' => 11,
                'field' => 'flow_temp_gauge_value',
                'tmv' => NULL,
                'nonconform_type' => 'Flow Temperature Gauge',
                'hazard_name' => 'Flow Temperature Gauge',
                'hazard_type' => '23',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            114 =>
            array (
                'id' => 118,
                'template_id' => 11,
                'field' => 'return_temp_gauge_value',
                'tmv' => NULL,
                'nonconform_type' => 'Return Temperature Gauge',
                'hazard_name' => 'Return Temperature Gauge',
                'hazard_type' => '47',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '45',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            115 =>
            array (
                'id' => 119,
                'template_id' => 12,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            116 =>
            array (
                'id' => 120,
                'template_id' => 12,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            117 =>
            array (
                'id' => 121,
                'template_id' => 12,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            118 =>
            array (
                'id' => 122,
                'template_id' => 12,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            119 =>
            array (
                'id' => 123,
                'template_id' => 12,
                'field' => 'stored_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Storage Temperature',
                'hazard_name' => 'Storage Temperature',
                'hazard_type' => '54',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '60',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            120 =>
            array (
                'id' => 124,
                'template_id' => 12,
                'field' => 'flow_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            121 =>
            array (
                'id' => 125,
                'template_id' => 12,
                'field' => 'return_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Return Temperature',
                'hazard_name' => 'Return Temperature',
                'hazard_type' => '46',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '45',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            122 =>
            array (
                'id' => 126,
                'template_id' => 13,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            123 =>
            array (
                'id' => 127,
                'template_id' => 13,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            124 =>
            array (
                'id' => 128,
                'template_id' => 13,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            125 =>
            array (
                'id' => 129,
                'template_id' => 13,
                'field' => 'flow_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            126 =>
            array (
                'id' => 130,
                'template_id' => 13,
                'field' => 'return_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Return Temperature',
                'hazard_name' => 'Return Temperature',
                'hazard_type' => '46',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '45',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            127 =>
            array (
                'id' => 131,
                'template_id' => 16,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            128 =>
            array (
                'id' => 132,
                'template_id' => 16,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            129 =>
            array (
                'id' => 133,
                'template_id' => 16,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            130 =>
            array (
                'id' => 134,
                'template_id' => 16,
                'field' => 'pipe_insulation',
                'tmv' => NULL,
                'nonconform_type' => 'Pipe Insulation',
                'hazard_name' => 'Pipe Insulation',
                'hazard_type' => '44',
                'answer_type' => 'multi_select',
                'value' => '222',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            131 =>
            array (
                'id' => 135,
                'template_id' => 16,
                'field' => 'pipe_insulation_condition',
                'tmv' => NULL,
                'nonconform_type' => 'Pipework Insulation Condition',
                'hazard_name' => 'Pipework Insulation Condition',
                'hazard_type' => '62',
                'answer_type' => 'dropdown',
                'value' => '203,204,205',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            132 =>
            array (
                'id' => 136,
                'template_id' => 16,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            133 =>
            array (
                'id' => 137,
                'template_id' => 16,
                'field' => 'hot_flow_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Hot Flow Temperature',
                'hazard_name' => 'Hot Flow Temperature',
                'hazard_type' => '74',
                'answer_type' => 'temp',
                'value' => '',
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            134 =>
            array (
                'id' => 138,
                'template_id' => 16,
                'field' => 'cold_flow_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Cold Flow Temperature',
                'hazard_name' => 'Cold Flow Temperature',
                'hazard_type' => '75',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20',
                'check_equal' => 1,
            ),
            135 =>
            array (
                'id' => 139,
                'template_id' => 16,
                'field' => 'ph',
                'tmv' => NULL,
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
                'check_equal' => 1,
            ),
            136 =>
            array (
                'id' => 140,
                'template_id' => 14,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            137 =>
            array (
                'id' => 141,
                'template_id' => 14,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            138 =>
            array (
                'id' => 142,
                'template_id' => 14,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            // 139 =>
            // array (
            //     'id' => 143,
            //     'template_id' => 14,
            //     'field' => 'aerosol_risk',
            //     'tmv' => NULL,
            //     'nonconform_type' => 'Aerosol Risk',
            //     'hazard_name' => 'Aerosol Risk',
            //     'hazard_type' => '1',
            //     'answer_type' => 'dropdown',
            //     'value' => '199,200',
            //     'value_max' => NULL,
            //     'value_min' => NULL,
            //     'check_equal' => 0,
            // ),
            140 =>
            array (
                'id' => 144,
                'template_id' => 14,
                'field' => 'pipe_insulation',
                'tmv' => NULL,
                'nonconform_type' => 'Pipe Insulation',
                'hazard_name' => 'Pipe Insulation',
                'hazard_type' => '44',
                'answer_type' => 'multi_select',
                'value' => '222',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            141 =>
            array (
                'id' => 145,
                'template_id' => 14,
                'field' => 'pipe_insulation_condition',
                'tmv' => NULL,
                'nonconform_type' => 'Pipework Insulation Condition',
                'hazard_name' => 'Pipework Insulation Condition',
                'hazard_type' => '62',
                'answer_type' => 'dropdown',
                'value' => '203,204,205',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            142 =>
            array (
                'id' => 146,
                'template_id' => 14,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            143 =>
            array (
                'id' => 147,
                'template_id' => 14,
                'field' => 'flow_temp',
                'tmv' => 0,
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            144 =>
            array (
                'id' => 148,
                'template_id' => 14,
                'field' => 'flow_temp',
                'tmv' => 1,
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '39',
                'value_min' => '43',
                'check_equal' => 0,
            ),
            145 =>
            array (
                'id' => 149,
                'template_id' => 14,
                'field' => 'ph',
                'tmv' => NULL,
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
                'check_equal' => 1,
            ),
            146 =>
            array (
                'id' => 150,
                'template_id' => 9,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            147 =>
            array (
                'id' => 151,
                'template_id' => 9,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            148 =>
            array (
                'id' => 152,
                'template_id' => 9,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            // 149 =>
            // array (
            //     'id' => 153,
            //     'template_id' => 9,
            //     'field' => 'aerosol_risk',
            //     'tmv' => NULL,
            //     'nonconform_type' => 'Aerosol Risk',
            //     'hazard_name' => 'Aerosol Risk',
            //     'hazard_type' => '1',
            //     'answer_type' => 'dropdown',
            //     'value' => '199,200',
            //     'value_max' => NULL,
            //     'value_min' => NULL,
            //     'check_equal' => 0,
            // ),
            150 =>
            array (
                'id' => 154,
                'template_id' => 9,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            151 =>
            array (
                'id' => 155,
                'template_id' => 9,
                'field' => 'flow_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Flow Temperature',
                'hazard_name' => 'Flow Temperature',
                'hazard_type' => '22',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20',
                'check_equal' => 1,
            ),
            152 =>
            array (
                'id' => 156,
                'template_id' => 9,
                'field' => 'ph',
                'tmv' => NULL,
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
                'check_equal' => 1,
            ),
            153 =>
            array (
                'id' => 157,
                'template_id' => 15,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            154 =>
            array (
                'id' => 158,
                'template_id' => 15,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            155 =>
            array (
                'id' => 159,
                'template_id' => 15,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            156 =>
            array (
                'id' => 160,
                'template_id' => 15,
                'field' => 'pipe_insulation',
                'tmv' => NULL,
                'nonconform_type' => 'Pipe Insulation',
                'hazard_name' => 'Pipe Insulation',
                'hazard_type' => '44',
                'answer_type' => 'multi_select',
                'value' => '222',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            157 =>
            array (
                'id' => 161,
                'template_id' => 15,
                'field' => 'pipe_insulation_condition',
                'tmv' => NULL,
                'nonconform_type' => 'Pipework Insulation Condition',
                'hazard_name' => 'Pipework Insulation Condition',
                'hazard_type' => '62',
                'answer_type' => 'dropdown',
                'value' => '203,204,205',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            158 =>
            array (
                'id' => 162,
                'template_id' => 15,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            // 159 =>
            // array (
            //     'id' => 163,
            //     'template_id' => 15,
            //     'field' => 'aerosol_risk',
            //     'tmv' => NULL,
            //     'nonconform_type' => 'Aerosol Risk',
            //     'hazard_name' => 'Aerosol Risk',
            //     'hazard_type' => '1',
            //     'answer_type' => 'dropdown',
            //     'value' => '199,200',
            //     'value_max' => NULL,
            //     'value_min' => NULL,
            //     'check_equal' => 0,
            // ),
            160 =>
            array (
                'id' => 164,
                'template_id' => 15,
                'field' => 'top_temp',
                'tmv' => 0,
                'nonconform_type' => 'Top Temperature',
                'hazard_name' => 'Top Temperature',
                'hazard_type' => '58',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            161 =>
            array (
                'id' => 165,
                'template_id' => 15,
                'field' => 'bottom_temp',
                'tmv' => 0,
                'nonconform_type' => 'Bottom Temperature',
                'hazard_name' => 'Bottom Temperature',
                'hazard_type' => '63',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20',
                'check_equal' => 1,
            ),
            162 =>
            array (
                'id' => 166,
                'template_id' => 15,
                'field' => 'ph',
                'tmv' => NULL,
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
                'check_equal' => 1,
            ),
            163 =>
            array (
                'id' => 167,
                'template_id' => 17,
                'field' => 'operational_use',
                'tmv' => NULL,
                'nonconform_type' => 'Operational Use',
                'hazard_name' => 'Operational Use',
                'hazard_type' => '40',
                'answer_type' => 'dropdown',
                'value' => '70',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            164 =>
            array (
                'id' => 168,
                'template_id' => 17,
                'field' => 'state',
                'tmv' => NULL,
                'nonconform_type' => 'Inaccessible Equipment',
                'hazard_name' => 'Inaccessible Equipment',
                'hazard_type' => '28',
                'answer_type' => 'boolean',
                'value' => '0',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            165 =>
            array (
                'id' => 169,
                'template_id' => 17,
                'field' => 'frequency_use',
                'tmv' => NULL,
                'nonconform_type' => 'Frequency of Use',
                'hazard_name' => 'Frequency of Use',
                'hazard_type' => '24',
                'answer_type' => 'dropdown',
                'value' => '1,2',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            166 =>
            array (
                'id' => 170,
                'template_id' => 17,
                'field' => 'cleanliness',
                'tmv' => NULL,
                'nonconform_type' => 'Equipment Cleanliness',
                'hazard_name' => 'Equipment Cleanliness',
                'hazard_type' => '16',
                'answer_type' => 'dropdown',
                'value' => '33,34,35',
                'value_max' => NULL,
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            167 =>
            array (
                'id' => 171,
                'template_id' => 17,
                'field' => 'ph',
                'tmv' => NULL,
                'nonconform_type' => 'PH',
                'hazard_name' => 'PH',
                'hazard_type' => '43',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '6.5',
                'value_min' => '8.5',
                'check_equal' => 1,
            ),
            168 =>
            array (
                'id' => 172,
                'template_id' => 17,
                'field' => 'pre_tmv_cold_flow_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Pre-TMV Cold Flow Temperature',
                'hazard_name' => 'Pre-TMV Cold Flow Temperature',
                'hazard_type' => '76',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => NULL,
                'value_min' => '20',
                'check_equal' => 1,
            ),
            169 =>
            array (
                'id' => 173,
                'template_id' => 17,
                'field' => 'pre_tmv_hot_flow_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Pre-TMV Hot Flow Temperature',
                'hazard_name' => 'Pre-TMV Hot Flow Temperature',
                'hazard_type' => '77',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '50',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
            170 =>
            array (
                'id' => 174,
                'template_id' => 17,
                'field' => 'post_tmv_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Post-TMV Temperature',
                'hazard_name' => 'Post-TMV Temperature',
                'hazard_type' => '78',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '39',
                'value_min' => '43',
                'check_equal' => 0,
            ),
            171 =>
                array (
                    'id' => 175,
                    'template_id' => 13,
                    'field' => 'cleanliness',
                    'tmv' => NULL,
                    'nonconform_type' => 'Equipment Cleanliness',
                    'hazard_name' => 'Equipment Cleanliness',
                    'hazard_type' => '16',
                    'answer_type' => 'dropdown',
                    'value' => '33,34,35',
                    'value_max' => NULL,
                    'value_min' => NULL,
                    'check_equal' => 0,
                ),

            172 =>
            array (
                'id' => 176,
                'template_id' => 10,
                'field' => 'return_temp',
                'tmv' => NULL,
                'nonconform_type' => 'Return Temperature',
                'hazard_name' => 'Return Temperature',
                'hazard_type' => '46',
                'answer_type' => 'temp',
                'value' => NULL,
                'value_max' => '45',
                'value_min' => NULL,
                'check_equal' => 0,
            ),
        ));


    }
}
