<?php

use Illuminate\Database\Seeder;

class TblDropdownDataAreaTableSeedMasterSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('tbl_dropdown_data_area')->delete();

        \DB::table('tbl_dropdown_data_area')->insert(array (
            0 =>
                array (
                    'id' => 2362,
                    'description' => 'Confined Space',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            1 =>
                array (
                    'id' => 2363,
                    'description' => 'Denied Access',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            2 =>
                array (
                    'id' => 2364,
                    'description' => 'Excessive Storage',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            3 =>
                array (
                    'id' => 2365,
                    'description' => 'Excessive Waste',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            4 =>
                array (
                    'id' => 2366,
                    'description' => 'No Keys',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            5 =>
                array (
                    'id' => 2367,
                    'description' => 'Locked',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            6 =>
                array (
                    'id' => 2368,
                    'description' => 'Height Restriction',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            7 =>
                array (
                    'id' => 2369,
                    'description' => 'Restricted Access',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            8 =>
                array (
                    'id' => 2370,
                    'description' => 'Room/location Occupied',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            9 =>
                array (
                    'id' => 2371,
                    'description' => 'Structurally Unsafe',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            10 =>
                array (
                    'id' => 2372,
                    'description' => 'Unsafe Access',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            11 =>
                array (
                    'id' => 2373,
                    'description' => 'Fixed Ceiling Tiles',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            12 =>
                array (
                    'id' => 2374,
                    'description' => 'Parquet Flooring',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            13 =>
                array (
                    'id' => 2375,
                    'description' => 'Listed Decoration/feature',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            14 =>
                array (
                    'id' => 2376,
                    'description' => 'Sealed Floor',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            15 =>
                array (
                    'id' => 2377,
                    'description' => 'Damage to Decoration',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            16 =>
                array (
                    'id' => 2378,
                    'description' => 'Other',
                    'dropdown_area_id' => 906,
                    'order' => 0,
                    'score' => 0,
                    'other' => 0,
                    'decommissioned' => 0,
                    'parent_id' => 0,
                    'removal_cost' => NULL,
                    'deleted_by' => NULL,
                    'created_by' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
        ));


    }
}
