<?php

namespace App\Http\Request\ShineCompliance\Equipment;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
class EquipmentRequest extends FormRequest
{
    public function rules()
    {
        return [
            'name' => 'required|string|max:255',
            'type' => 'required',
            'assess_id' => 'nullable',
            'property_id' => 'nullable',
            'state' => 'nullable',
            'reason' => 'nullable',
            'area_id' => 'required',
            // 'area_description' => 'required_if:area_id,=,-1',
            'area_description' => 'nullable',
            'area_reference' => 'required_if:area_id,-1',
            'location_id' => 'required',
            'location_description' => 'nullable',
            'location_reference' => 'required_if:location_id,-1',
            'decommissioned' => 'nullable',
            'operational_use' => 'required',
            'accessibility' => 'nullable',
            'reason_other' => 'nullable',
            'parent_id' => 'nullable',
            'hot_parent_id' => 'nullable',
            'cold_parent_id' => 'nullable',
            'system_id' => 'nullable',
            'specificLocations1' => 'nullable',
            'specificLocations2' => 'nullable',
            'specificLocations3' => 'nullable',
            'specificLocations_other' => 'nullable',
            'frequency_use' => 'required',
            'extent' => 'nullable',
            'manufacturer' => 'nullable',
            'model' => 'nullable',
            'dimensions_length' => 'nullable',
            'dimensions_width' => 'nullable',
            'dimensions_depth' => 'nullable',
            'capacity' => 'nullable',
            'stored_water' => 'nullable',
            'aerosol_risk' => 'nullable',
            'flexible_hose' => 'nullable',
            'sentinel' => 'nullable',
            'nearest_furthest' => 'nullable',
            'tmv_fitted' => 'nullable',
            'labelling' => 'nullable',
            'pipe_insulation' => 'nullable',
            'pipe_insulation_condition' => 'nullable',
            'horizontal_vertical' => 'nullable',
            'construction_material' => 'nullable',
            'insulation_type' => 'nullable',
            'insulation_thickness' => 'nullable',
            'insulation_condition' => 'nullable',
            'anti_stratification' => 'nullable',
            'direct_fired' => 'nullable',
            'water_softener' => 'nullable',
            'system_recirculated' => 'nullable',
            'drain_valve' => 'nullable',
            'flow_temp_gauge' => 'nullable',
            'return_temp_gauge' => 'nullable',
            'source' => 'nullable',
            'source_accessibility' => 'nullable',
            'source_condition' => 'nullable',
            'rodent_protection' => 'nullable',
            'backflow_protection' => 'nullable',
            'screened_lid_vent' => 'nullable',
            'air_vent' => 'nullable',
            'warning_pipe' => 'nullable',
            'overflow_pipe' => 'nullable',
            'drain_size' => 'nullable',
            'drain_location' => 'nullable',
            'cold_feed_size' => 'nullable',
            'cold_feed_location' => 'nullable',
            'outlet_size' => 'nullable',
            'outlet_location' => 'nullable',
            'can_isolated' => 'nullable',
            'main_access_hatch' => 'nullable',
            'ball_valve_hatch' => 'nullable',
            'operational_exposure' => 'nullable',
            'envidence_stagnation' => 'nullable',
            'degree_fouling' => 'nullable',
            'degree_biological' => 'nullable',
            'extent_corrosion' => 'nullable',
            'cleanliness' => 'nullable',
            'ease_cleaning' => 'nullable',
            'comments' => 'nullable',
            'inlet_temp' => 'nullable',
            'stored_temp' => 'nullable',
            'flow_temp' => 'nullable',
            'return_temp' => 'nullable',
            'top_temp' => 'nullable',
            'bottom_temp' => 'nullable',
            'flow_temp_gauge_value' => 'nullable',
            'return_temp_gauge_value' => 'nullable',
            'ph' => 'nullable',
            'photoLocation' => 'nullable',
            'photoEquipment' => 'nullable',
            'photoAdditional' => 'nullable',
            'has_sample' => 'nullable',
            'sample_reference' => 'nullable',
            'access' => 'nullable',
            'water_meter_fitted' => 'nullable',
            'water_meter_reading' => 'nullable',
            'material_of_pipework' => 'nullable',
            'material_of_pipework-other' => 'nullable',
            'hot_flow_temp' => 'nullable',
            'cold_flow_temp' => 'nullable',
            'size_of_pipework' => 'nullable',
            'condition_of_pipework' => 'nullable',
            'stop_tap_fitted' => 'nullable',
            'ambient_area_temp' => 'nullable',
            'incoming_main_pipe_work_temp' => 'nullable',
            'pre_tmv_cold_flow_temp' => 'nullable',
            'pre_tmv_hot_flow_temp' => 'nullable',
            'post_tmv_temp' => 'nullable',
            'construction_return_temp' => 'nullable',
            'mixed_temp' => 'nullable',
        ];
    }
     /**
     * Custom message for validation
     *
     * @return array
     */
    public function messages()
    {
        return [
            'area_reference.required_if' => 'The area reference field is required ',
            'location_reference.required_if' => 'The location reference field is required ',
        ];
    }

}
