<div class="offset-top40">
    @include('shineCompliance.forms.form_input_small',['title' => 'Flow Temperature:', 'name' => 'flow_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Inlet Temperature:', 'name' => 'inlet_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Stored Temperature:', 'name' => 'stored_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Return Temperature:', 'name' => 'return_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Top Temperature:', 'name' => 'top_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Bottom Temperature:', 'name' => 'bottom_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Flow Temperature Gauge:', 'name' => 'flow_temp_gauge_value', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Return Temperature Gauge:', 'name' => 'return_temp_gauge_value', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Mixed Temperature:', 'name' => 'mixed_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Ambient Area Temperature:', 'name' => 'ambient_area_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Incoming Main Pipework Surface Temperature:', 'name' => 'incoming_main_pipe_work_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Hot Flow Temperature:', 'name' => 'hot_flow_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Cold Flow Temperature:', 'name' => 'cold_flow_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Pre-TMV Cold Flow Temperature:', 'name' => 'pre_tmv_cold_flow_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Pre-TMV Hot Flow Temperature:', 'name' => 'pre_tmv_hot_flow_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'Post-TMV Temperature:', 'name' => 'post_tmv_temp', 'data' =>'' ,'measurement' => '°C','class_other' => 'equipment_section'])
    @include('shineCompliance.forms.form_input_small',['title' => 'pH:', 'name' => 'ph', 'data' =>'' ,'measurement' => 'pH','class_other' => 'equipment_section'])
</div>
